- blogs
  - [today](blogs/today.md)
  - [readme](blogs/readme.md)
  - sub folder
    - subsub folder
      - [a file](blogs/sub%20folder/subsub%20folder/a%20file.md)
    - [readme](blogs/sub%20folder/readme.md)
- docs
  - [chapter1](docs/chapter1.md)
  - [readme](docs/readme.md)
- [readme](readme.md)
- [directory_tree](directory_tree.md)
